@include('pago.pag_showFields.estatusPago')
@include('pago.pag_showFields.formaDePago')
@include('pago.pag_showFields.montoDePago')
@include('pago.pag_showFields.numeroDePedido')
@include('pago.pag_showFields.tipo')