<?php
return array(
/* ===================== PERFIL [ PERSONALIZAR SISTEMA ] ===================== */
  'select_idioma' => [
    ''            => 'Seleccione. . .',
    'es'          => 'Español',
    'en'          => 'Ingles',
  ],
  'select_color_barra_de_navegacion'  => [
    ''                              => 'Seleccione. . .',
    'navbar-dark navbar-primary'    => 'navbar-dark navbar-primary',
    'navbar-dark navbar-secondary'  => 'navbar-dark navbar-secondary',
    'navbar-dark navbar-info'       => 'navbar-dark navbar-info',
    'navbar-dark navbar-success'    => 'navbar-dark navbar-success',
    'navbar-dark navbar-danger'     => 'navbar-dark navbar-danger',
    'navbar-dark navbar-indigo'     => 'navbar-dark navbar-indigo',
    'navbar-dark navbar-purple'     => 'navbar-dark navbar-purple',
    'navbar-dark navbar-pink'       => 'navbar-dark navbar-pink',
    'navbar-dark navbar-teal'       => 'navbar-dark navbar-teal',
    'navbar-dark navbar-cyan'       => 'navbar-dark navbar-cyan',
    'navbar-dark'                   => 'navbar-dark',
    'navbar-dark navbar-gray-dark'  => 'navbar-dark navbar-gray-dark',
    'navbar-dark navbar-gray'       => 'navbar-dark navbar-gray',
    'navbar-light'                  => 'navbar-light',
    'navbar-light navbar-warning'   => 'navbar-light navbar-warning',
    'navbar-light navbar-white'     => 'navbar-light navbar-white',
    'navbar-light navbar-orange'    => 'navbar-light navbar-orange',
  ],
  'select_color_barra_lateral_oscura_o_clara'  => [
    ''                      => 'Seleccione. . .',
    'sidebar-dark-primary'  => 'sidebar-dark-primary',
    'sidebar-dark-warning'  => 'sidebar-dark-warning',
    'sidebar-dark-info'     => 'sidebar-dark-info',
    'sidebar-dark-danger'   => 'idebar-dark-danger',
    'sidebar-dark-success'  => 'sidebar-dark-success',
    'sidebar-dark-indigo'   => 'sidebar-dark-indigo',
    'sidebar-dark-navy'     => 'sidebar-dark-navy',
    'sidebar-dark-purple'   => 'sidebar-dark-purple',
    'sidebar-dark-fuchsia'  => 'sidebar-dark-fuchsia',
    'sidebar-dark-pink'     => 'sidebar-dark-pink',
    'sidebar-dark-maroon'   => 'sidebar-dark-maroon',
    'sidebar-dark-orange'   => 'sidebar-dark-orange',
    'sidebar-dark-lime'     => 'sidebar-dark-lime',
    'sidebar-dark-teal'     => 'sidebar-dark-teal',
    'sidebar-dark-olive'    => 'sidebar-dark-olive',
    'sidebar-light-primary' => 'sidebar-light-primary',
    'sidebar-light-warning' => 'sidebar-light-warning',
    'sidebar-light-info'    => 'sidebar-light-info',
    'sidebar-light-danger'  => 'sidebar-light-danger',
    'sidebar-light-success' => 'sidebar-light-success',
    'sidebar-light-indigo'  => 'sidebar-light-indigo',
    'sidebar-light-navy'    => 'sidebar-light-navy',
    'sidebar-light-purple'  => 'sidebar-light-purple',
    'sidebar-light-fuchsia' => 'sidebar-light-fuchsia',
    'sidebar-light-pink'    => 'sidebar-light-pink',
    'sidebar-light-maroon'  => 'sidebar-light-maroon',
    'sidebar-light-orange'  => 'sidebar-light-orange',
    'sidebar-light-lime'    => 'sidebar-light-lime',
    'sidebar-light-teal'    => 'sidebar-light-teal',
    'sidebar-light-olive'   => 'sidebar-light-olive',
  ],
  'select_color_logotipo'  => [
    ''                  => 'Seleccione. . .',
    'navbar-primary'    => 'navbar-primary',
    'navbar-secondary'  => 'navbar-secondary',
    'navbar-info'       => 'navbar-info',
    'navbar-success'    => 'navbar-success',
    'navbar-danger'     => 'navbar-danger',
    'navbar-indigo'     => 'navbar-indigo',
    'navbar-purple'     => 'navbar-purple',
    'navbar-pink'       => 'navbar-pink',
    'navbar-teal'       => 'navbar-teal',
    'navbar-cyan'       => 'avbar-cyan',
    'navbar-dark'       => 'navbar-dark',
    'navbar-gray-dark'  => 'navbar-gray-dark',
    'navbar-gray'       => 'navbar-gray',
    'navbar-light'      => 'navbar-light',
    'navbar-warning'    => 'navbar-warning',
    'navbar-white'      => 'navbar-white',
    'navbar-orange'     => 'navbar-orange',
  ],
/* ===================== PERFIL [ ACTIVIDAD ] ===================== */
  'select_perfil_actividad_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'inpu'                => 'Input',
    'ant'                 => 'Valor anterior',
    'nuev'                => 'Nuevo valor',
    'created_at'          => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== PERFIL [ NOTIFICACIONES ] ===================== */
  'select_perfil_notificacion_index'  => [
    ''                    => 'Buscar por. . .',
    'data'                => 'Asunto',
    'created_at'          => 'Fecha (YYYY-MM-DD)',
  ],
  /* ===================== PERFIL [ ARCHIVOS GENERADOS ] ===================== */
  'select_perfil_archivoGenerado_index'  => [
    ''                    => 'Buscar por. . .',
    'data'                => 'Nombre',
    'created_at'          => 'Fecha (YYYY-MM-DD)',
  ],
/* ===================== SISTEMA [ PLANTILLAS ] ===================== */
  'select_plantilla_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre de la plantilla',
    'mod'                 => 'Módulo',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_modulo' => [
    ''              => 'Seleccione . . .',
    'Cotizaciones'  => 'Cotizaciones',
    'Clientes'      => 'Clientes',
    'Perfil'        => 'Perfil',
    'Sistema'       => 'Sistema',
    'Usuarios'      => 'Usuarios',
    'Ventas'        => 'Ventas',
  ],
/* ===================== SISTEMA [ ACTIVIDAD ] ===================== */
  'select_sistema_actividad_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'inpu'                => 'Input',
    'usu'                 => 'Usuario',
    'ant'                 => 'Valor anterior',
    'nuev'                => 'Nuevo valor',
    'created_at'          => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== SISTEMA [ CATÁLOGOS ] ===================== */
  'select_catalogo_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'input'               => 'Input',
    'vista'               => 'Vista',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_input'  => [
    'Armados (Gama)'        => 'Armados (Gama)',
    'Armados (Tipo)'        => 'Armados (Tipo)',
    'Productos (Categoría)' => 'Productos (Categoría)',
    'Productos (Etiqueta)'  => 'Productos (Etiqueta)',
  ],
/* ===================== SISTEMA [ SERIES ] ===================== */
  'select_serie_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'input'               => 'Input',
    'vista'               => 'Vista',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_input_serie'      => [
    'Cotizaciones (Serie)'  => 'Cotizaciones (Serie)',
    'Pedidos (Serie)'       => 'Pedidos (Serie)',
  ],
/* ===================== [ USUARIOS ] ===================== */
  'select_usuario_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre',
    'email_registro'      => 'Correo de registro',
    'email'               => 'Correo para acceder',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ CLIENTES ] ===================== */
  'select_cliente_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre',
    'email_registro'      => 'Correo de registro',
    'email'               => 'Correo para acceder',
    'emp'                 => 'Empresa',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ ROLES ] ===================== */
  'select_rol_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre del rol',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PERMISOS ] ===================== */
  'select_rol__permiso_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre del permiso',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PAPELERA DE RECICLAJE ] ===================== */
  'select_papeleraDeReciclaje_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ], 
/* ===================== [ PROVEEDOR ] ===================== */
  'select_proveedor_index'      => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'raz_soc'       => 'Razón social',
    'nom_comerc'    => 'Nombre comercial',
    'nom_rep_legal' => 'Nombre del representante legal',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_fabricante_distribuidor_index'  => [
    ''              => 'Seleccione. . .',
    'Fabricante'    => 'Fabricante',
    'Distribuidor'  => 'Distribuidor',
  ],
/* ===================== PROVEEDOR [ CONTACTO ] ===================== */
  'select_contactos_proveedor_index'  => [
    ''            => 'Buscar por. . .',
    'id'          => 'ID',
    'carg'        => 'Cargo',
    'nom'         => 'Nombre',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ ARMADOS ] ===================== */
  'select_armado_index'  => [
    ''            => 'Buscar por. . .',
    'id'          => 'ID',
    'nom'         => 'Nombre',
    'prec_redond' => 'Precio redondeado',
    'sku'         => 'SKU',
    'gama'        => 'Gama',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_tipo'  => [
    ''            => 'Seleccione. . .',
    'Producto'    => 'Producto',
    'Canasta'     => 'Canasta',
  ],
  'select_producto_armado_index'  => [
    ''                        => 'Buscar por. . .',
    'productos.categ'         => 'Categoría',
    'productos.cod_barras'    => 'Código de barras',
    'productos.etiq'          => 'Etiqueta',
    'productos.id'            => 'ID',
    'productos.prec_clien'    => 'Precio cliente',
    'productos.produc'        => 'Producto',
    'productos.prove'         => 'Proveedor',
    'productos.sku'           => 'SKU',
  ],
  'select_cantidad_table_productos_edit'  => [
    '1' => 1,
    '2' => 2,
    '3' => 3,
    '4' => 4,
    '5' => 5,
    '6' => 6,
    '7' => 7,
    '8' => 8,
    '9' => 9,
    '10' => 10,
    '11' => 11,
    '12' => 12,
    '13' => 13,
    '14' => 14,
    '15' => 15,
    '16' => 16,
    '17' => 17,
    '18' => 18,
    '19' => 19,
    '20' => 20
  ],
  'select_destacado'  => [
    ''            => 'Seleccione. . .',
    'Si'          => 'Si',
    'No'          => 'No',
  ],
/* ===================== [ PRODUCTOS ] ===================== */
  'select_producto_index'  => [
    ''              => 'Buscar por. . .',
    'categ'         => 'Categoría',
    'cod_barras'    => 'Código de barras',
    'etiq'          => 'Etiqueta',
    'id'            => 'ID',
    'prec_clien'    => 'Precio cliente',
    'produc'        => 'Producto',
    'prove'         => 'Proveedor',
    'sku'           => 'SKU',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_utilidad' => [
    ''              => 'Seleccione. . .',
    '.1'           => '10%',
    '.2'           => '20%',
    '.3'           => '30%',
    '.4'           => '40%',
    '.5'           => '50%',
    '.6'           => '60%',
    '.7'           => '70%',
    '.8'           => '80%',
    '.9'           => '90%',
  ],
  'select_utilidad_sin_seleccione' => [
    '.1'           => '10%',
    '.2'           => '20%',
    '.3'           => '30%',
    '.4'           => '40%',
    '.5'           => '50%',
    '.6'           => '60%',
    '.7'           => '70%',
    '.8'           => '80%',
    '.9'           => '90%',
  ],
/*
  'select_sustituto_index'  => [
    ''              => 'Buscar por. . .',
    'categ'         => 'Categoría',
    'etiq'          => 'Etiqueta',
    'productos.id'  => 'ID',
    'prec_clien'    => 'Precio cliente',
    'produc'        => 'Producto',
    'prove'         => 'Proveedor',
    'sku'           => 'SKU',
  ],
  'select_proveedor_producto_index'  => [
    ''                                         => 'Buscar por. . .',
    'proveedores.nom_comerc'                   => 'Proveedor',
    'producto_tiene_proveedores.prec_prove'    => 'Pecio proveedor',
    'producto_tiene_proveedores.utilid'        => 'Utilidad',
    'producto_tiene_proveedores.prec_clien'    => 'Precio cliente',
  ],
*/
/* ===================== [ COTIZACIONES ] ===================== */
  'select_cotizacion_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'Serie',
    'email_nombre'        => 'Nombre',
    'email_cliente'       => 'Correo',
    'tot'                 => 'Total',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== VENTAS [ PEDIDO ACTIVO ] ===================== */
  'select_venta_pedidoActivo_index'  => [
    ''                        => 'Buscar por. . .',
    'usuario.email_registro'  => 'Cliente', // este marca error
    'estat_pag'               => 'Estatus pago',
    'estat_vent_gen'          => 'Estatus venta general',
    'estat_vent_arm'          => 'Estatus venta armado(s)',
    'estat_vent_dir'          => 'Estatus venta dirección(es)',
    'fech_de_entreg'          => 'Fecha de entrega',
    'id'                      => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',    
    'entr_xprs'               => '¿Express?',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_entrega_express'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'es_pedido_urgente'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_se_puede_entregar_antes'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_es_de_regalo'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
);