<?php
/* =====================  [ GLOBAL ] ===================== */
return array(
  'select_estado' => [
    'Aguascalientes'        => 'Aguascalientes',
    'Baja California'       => 'Baja California',
    'Baja California Sur'   => 'Baja California Sur',
    'Campeche'              => 'Campeche',
    'Ciudad de México'      => 'Ciudad de México',
    'Chihuahua'             => 'Chihuahua',
    'Chiapas'               => 'Chiapas',
    'Coahuila de Zaragoza'  => 'Coahuila de Zaragoza',
    'Colima'                => 'Colima',
    'Durango'               => 'Durango',
    'Estado de México'      => 'Estado de México',
    'Guanajuato'            => 'Guanajuato',
    'Guerrero'              => 'Guerrero',
    'Hidalgo'               => 'Hidalgo',
    'Jalisco'               => 'Jalisco',
    'Michoacán de Ocampo'   => 'Michoacán de Ocampo',
    'Morelos'               => 'Morelos',
    'Nayarit'               => 'Nayarit',
    'Nuevo León'            => 'Nuevo León',
    'Oaxaca'                => 'Oaxaca',
    'Puebla'                => 'Puebla',
    'Querétaro'             => 'Querétaro',
    'Quintana Roo'          => 'Quintana Roo' ,
    'San Luis Potosí'       => 'San Luis Potosí',
    'Sinaloa'               => 'Sinaloa',
    'Sonora'                => 'Sonora',
    'Tabasco'               => 'Tabasco',
    'Tamaulipas'            => 'Tamaulipas',
    'Tlaxcala'              => 'Tlaxcala',
    'Veracruz'              => 'Veracruz',
    'Yucatán'               => 'Yucatán',
    'Zacatecas'             => 'Zacatecas',
  ],
  'select_si_no' => [
    'Si'          => 'Si',
    'No'          => 'No',
  ],
/* ===================== PERFIL [ PERSONALIZAR SISTEMA ] ===================== */
  'select_idioma' => [
    'es'          => 'Español',
    'en'          => 'Ingles',
  ],
  'select_color_barra_de_navegacion'  => [
    'navbar-dark navbar-primary'    => 'navbar-dark navbar-primary',
    'navbar-dark navbar-secondary'  => 'navbar-dark navbar-secondary',
    'navbar-dark navbar-info'       => 'navbar-dark navbar-info',
    'navbar-dark navbar-success'    => 'navbar-dark navbar-success',
    'navbar-dark navbar-danger'     => 'navbar-dark navbar-danger',
    'navbar-dark navbar-indigo'     => 'navbar-dark navbar-indigo',
    'navbar-dark navbar-purple'     => 'navbar-dark navbar-purple',
    'navbar-dark navbar-pink'       => 'navbar-dark navbar-pink',
    'navbar-dark navbar-teal'       => 'navbar-dark navbar-teal',
    'navbar-dark navbar-cyan'       => 'navbar-dark navbar-cyan',
    'navbar-dark'                   => 'navbar-dark',
    'navbar-dark navbar-gray-dark'  => 'navbar-dark navbar-gray-dark',
    'navbar-dark navbar-gray'       => 'navbar-dark navbar-gray',
    'navbar-light'                  => 'navbar-light',
    'navbar-light navbar-warning'   => 'navbar-light navbar-warning',
    'navbar-light navbar-white'     => 'navbar-light navbar-white',
    'navbar-light navbar-orange'    => 'navbar-light navbar-orange',
  ],
  'select_color_barra_lateral_derecha_oscura_o_clara'  => [
    'control-sidebar-light border-left' => 'control-sidebar-light border-left',
    'control-sidebar-dark'              => 'control-sidebar-dark',
  ],
  'select_color_barra_lateral_oscura_o_clara'  => [
    'sidebar-dark-primary'  => 'sidebar-dark-primary',
    'sidebar-dark-warning'  => 'sidebar-dark-warning',
    'sidebar-dark-info'     => 'sidebar-dark-info',
    'sidebar-dark-danger'   => 'sidebar-dark-danger',
    'sidebar-dark-success'  => 'sidebar-dark-success',
    'sidebar-dark-indigo'   => 'sidebar-dark-indigo',
    'sidebar-dark-navy'     => 'sidebar-dark-navy',
    'sidebar-dark-purple'   => 'sidebar-dark-purple',
    'sidebar-dark-fuchsia'  => 'sidebar-dark-fuchsia',
    'sidebar-dark-pink'     => 'sidebar-dark-pink',
    'sidebar-dark-maroon'   => 'sidebar-dark-maroon',
    'sidebar-dark-orange'   => 'sidebar-dark-orange',
    'sidebar-dark-lime'     => 'sidebar-dark-lime',
    'sidebar-dark-teal'     => 'sidebar-dark-teal',
    'sidebar-dark-olive'    => 'sidebar-dark-olive',
    'sidebar-light-primary' => 'sidebar-light-primary',
    'sidebar-light-warning' => 'sidebar-light-warning',
    'sidebar-light-info'    => 'sidebar-light-info',
    'sidebar-light-danger'  => 'sidebar-light-danger',
    'sidebar-light-success' => 'sidebar-light-success',
    'sidebar-light-indigo'  => 'sidebar-light-indigo',
    'sidebar-light-navy'    => 'sidebar-light-navy',
    'sidebar-light-purple'  => 'sidebar-light-purple',
    'sidebar-light-fuchsia' => 'sidebar-light-fuchsia',
    'sidebar-light-pink'    => 'sidebar-light-pink',
    'sidebar-light-maroon'  => 'sidebar-light-maroon',
    'sidebar-light-orange'  => 'sidebar-light-orange',
    'sidebar-light-lime'    => 'sidebar-light-lime',
    'sidebar-light-teal'    => 'sidebar-light-teal',
    'sidebar-light-olive'   => 'sidebar-light-olive',
  ],
  'select_color_logotipo'  => [
    'navbar-primary'    => 'navbar-primary',
    'navbar-secondary'  => 'navbar-secondary',
    'navbar-info'       => 'navbar-info',
    'navbar-success'    => 'navbar-success',
    'navbar-danger'     => 'navbar-danger',
    'navbar-indigo'     => 'navbar-indigo',
    'navbar-purple'     => 'navbar-purple',
    'navbar-pink'       => 'navbar-pink',
    'navbar-teal'       => 'navbar-teal',
    'navbar-cyan'       => 'navbar-cyan',
    'navbar-dark'       => 'navbar-dark',
    'navbar-gray-dark'  => 'navbar-gray-dark',
    'navbar-gray'       => 'navbar-gray',
    'navbar-light'      => 'navbar-light',
    'navbar-warning'    => 'navbar-warning',
    'navbar-white'      => 'navbar-white',
    'navbar-orange'     => 'navbar-orange',
  ],
/* ====================== ROL FERRO [ RUTAS ] ===================== */
  'select_rolFerro_ruta_index' => [ 
    ''    => 'Buscar por. . .',
    'id'  => 'Id',
    'nom' => 'Nombre de la ruta',
  ],
/* ===================== JOBS [ JOBS ] ===================== */
  'select_job_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'queue'               => 'Queue',
    'payload'             => 'Payload',
    'created_at'          => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== JOBS [ FAILED JOBS ] ===================== */
  'select_failed_job_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'queue'               => 'Queue',
  ],
/* ===================== PERFIL [ ACTIVIDAD ] ===================== */
  'select_perfil_actividad_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'inpu'                => 'Input',
    'ant'                 => 'Valor anterior',
    'nuev'                => 'Nuevo valor',
    'created_at'          => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== PERFIL [ NOTIFICACIONES ] ===================== */
  'select_perfil_notificacion_index'  => [
    ''                    => 'Buscar por. . .',
    'data'                => 'Asunto',
    'created_at'          => 'Fecha (YYYY-MM-DD)',
  ],
  /* ===================== PERFIL [ ARCHIVOS GENERADOS ] ===================== */
  'select_perfil_archivoGenerado_index'  => [
    ''                    => 'Buscar por. . .',
    'data'                => 'Nombre',
    'created_at'          => 'Fecha (YYYY-MM-DD)',
  ],
/* ===================== SISTEMA [ PLANTILLAS ] ===================== */
  'select_plantilla_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre de la plantilla',
    'mod'                 => 'Módulo',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_modulo' => [
    'Cotizaciones (Términos y condiciones)'     => 'Cotizaciones (Términos y condiciones)',
    'Clientes (Bienvenida)'                     => 'Clientes (Bienvenida)',
    'Facturación (Error del cliente)'           => 'Facturación (Error del cliente)',
    'Facturación (Factura generada)'            => 'Facturación (Factura generada)',
    'Facturación (Factura cancelada)'           => 'Facturación (Factura cancelada)',
    'Logística (Pedido entregado)'              => 'Logística (Pedido entregado)',
    'Pagos (Registrar pago)'                    => 'Pagos (Registrar pago)',
    'Pagos (Pago rechazado)'                    => 'Pagos (Pago rechazado)',
    'Perfil (Cambio de contraseña)'             => 'Perfil (Cambio de contraseña)',
    'Sistema (Restablecimiento de contraseña)'  => 'Sistema (Restablecimiento de contraseña)',
    'Usuarios (Bienvenida)'                     => 'Usuarios (Bienvenida)',
    'Ventas (Registrar pedido)'                 => 'Ventas (Registrar pedido)',
    'Ventas (Pedido cancelado)'                 => 'Ventas (Pedido cancelado)',
  ],
/* ===================== SISTEMA [ ACTIVIDAD ] ===================== */
  'select_sistema_actividad_index'  => [
    ''                        => 'Buscar por. . .',
    'id'                      => 'ID',
    'mod'                     => 'Módulo',
    'reg'                     => 'Registro',
    'inpu'                    => 'Input',
  //  'usuario.email_registro'  => 'Usuario',
    'ant'                     => 'Valor anterior',
    'nuev'                    => 'Nuevo valor',
    'created_at'              => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== SISTEMA [ CATÁLOGOS ] ===================== */
  'select_catalogo_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'input'               => 'Input',
    'vista'               => 'Vista',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_input'  => [
    'Armados (Gama)'                  => 'Armados (Gama)',
    'Armados (Tipo)'                  => 'Armados (Tipo)',
    'Productos (Categoría)'           => 'Productos (Categoría)',
    'Productos (Etiqueta)'            => 'Productos (Etiqueta)',
    'Soportes (Agrupación de fallas)' => 'Soportes (Agrupación de fallas)',
  ],
/* ===================== SISTEMA [ SERIES ] ===================== */
  'select_serie_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'input'               => 'Input',
    'vista'               => 'Vista',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_input_serie'      => [
    'Cotizaciones (Serie)'  => 'Cotizaciones (Serie)',
    'Pedidos (Serie)'       => 'Pedidos (Serie)',
  ],
  /* ===================== [ QUEJAS Y SUGERENCIAS ] ===================== */
  'select_qys_index'  => [
    ''                        => 'Buscar por. . .',
  //  'usuario.email_registro'  => 'Correo usuario',
    'tip'                     => 'Tipo',
    'depto'                   => 'Departamento',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_queja_o_sugerencia'  => [
    'Queja'                   => 'Queja',
    'Sugerencia'              => 'Sugerencia',
  ],
  'select_departamento' => [
    'Ventas'      => 'Ventas',
    'Producción'  => 'Producción',
    'Logística'   => 'Logística',
    'Facturación' => 'Facturación',
    'Sistema'     => 'Sistema',
    'Otro'        => 'Otro',
  ],
/* ===================== [ USUARIOS ] ===================== */
  'select_usuario_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre',
    'email_registro'      => 'Correo de registro',
    'email'               => 'Correo para acceder',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ CLIENTES ] ===================== */
  'select_cliente_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre',
    'email_registro'      => 'Correo de registro',
    'email'               => 'Correo para acceder',
    'emp'                 => 'Empresa',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  /* ===================== CLIENTES [ COTIZACIONES ] ===================== */
  'select_cliente_cotizacion_index'  => [
    ''                        => 'Buscar por. . .',
    'serie'                   => 'Serie',
    'estat'                   => 'Estatus',
    'valid'                   => 'Validez',
    'tot'                     => 'Total',
    'created_at'              => 'Fecha de creación (YYYY-MM-DD)',
  ],
/* ===================== CLIENTES [ PEDIDOS ] ===================== */
  'select_cliente_pedido_index'  => [
    ''                        => 'Buscar por. . .',
    'estat_pag'               => 'Estatus pago',
    'fech_de_entreg'          => 'Fecha de entrega',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',    
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== CLIENTES [ FACTURAS ] ===================== */
  'select_cliente_factura_index'  => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'est_fact'      => 'Estatus factura',
    'nom_o_raz_soc' => 'Nombre o razón social',
    'rfc'           => 'RFC',
  ],
/* ===================== CLIENTES [ QUEJAS Y SUGERENCIAS ] ===================== */
  'select_cliente_qys_index'  => [
    ''                        => 'Buscar por. . .',
    'depto'                   => 'Departamento',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ ROLES ] ===================== */
  'select_rol_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre del rol',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PERMISOS ] ===================== */
  'select_rol__permiso_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre del permiso',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PAPELERA DE RECICLAJE ] ===================== */
  'select_papeleraDeReciclaje_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== ROL CLIENTE [ DATOS FISCALES ] ===================== */
  'select_datos_fiscales_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'rfc'                 => 'RFC',
    'nom_o_raz_soc'       => 'Razón social',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== ROL CLIENTE [ DIRECCIONES ] ===================== */
  'select_direcciones_index'      => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'nom_ref_uno'   => 'Nombre de la persona que recibe uno',
    'nom_ref_dos'   => 'Nombre de la persona que recibe dos',
    'pais'          => 'País',
    'ciudad'        => 'Ciudad',
    'col'           => 'Colonia',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== ROL CLIENTES [ FACTURAS ] ===================== */
  'select_facturas_index'  => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'est_fact'      => 'Estatus factura',
    'nom_o_raz_soc' => 'Nombre o razón social',
    'rfc'           => 'RFC',
  ],
/* ===================== ROL CLIENTES [ PAGOS ] ===================== */
  'select_pagos_rol_cliente_index'  => [
      ''              => 'Buscar por. . .',
      'cod_fact'      => 'Código de facturación',
      'estat_pag'     => 'Estatus de pago',
      'form_de_pag'   => 'Forma de pago',
      'mont_de_pag'   => 'Monto de pago',
    //  'pedido.num_pedido' => 'Número de pedido',
  ],
/* ===================== [ PROVEEDOR ] ===================== */
  'select_proveedor_index'      => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'raz_soc'       => 'Razón social',
    'nom_comerc'    => 'Nombre comercial',
    'nom_rep_legal' => 'Nombre del representante legal',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_fabricante_distribuidor_index'  => [
    'Fabricante'    => 'Fabricante',
    'Distribuidor'  => 'Distribuidor',
  ],
/* ===================== PROVEEDOR [ CONTACTO ] ===================== */
  'select_contactos_proveedor_index'  => [
    ''            => 'Buscar por. . .',
    'id'          => 'ID',
    'carg'        => 'Cargo',
    'nom'         => 'Nombre',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ ARMADOS ] ===================== */
  'select_armado_index'  => [
    ''            => 'Buscar por. . .',
    'id'          => 'ID',
    'nom'         => 'Nombre',
    'prec_redond' => 'Precio redondeado',
    'sku'         => 'SKU',
    'gama'        => 'Gama',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_tipo'   => [
    'Producto'    => 'Producto',
    'Canasta'     => 'Canasta',
  ],
  'select_producto_armado_index'  => [
    ''              => 'Buscar por. . .',
    'categ'         => 'Categoría',
    'cod_barras'    => 'Código de barras',
    'etiq'          => 'Etiqueta',
    'productos.id'  => 'ID',
    'prec_clien'    => 'Precio cliente',
    'produc'        => 'Producto',
    'prove'         => 'Proveedor',
    'sku'           => 'SKU',
  ],
  'select_cantidad_table_productos_edit'  => [
    '1' => 1,
    '2' => 2,
    '3' => 3,
    '4' => 4,
    '5' => 5,
    '6' => 6,
    '7' => 7,
    '8' => 8,
    '9' => 9,
    '10' => 10,
    '11' => 11,
    '12' => 12,
    '13' => 13,
    '14' => 14,
    '15' => 15,
    '16' => 16,
    '17' => 17,
    '18' => 18,
    '19' => 19,
    '20' => 20
  ],
  'select_destacado'  => [
    'Si'          => 'Si',
    'No'          => 'No',
  ],
  'select_tamano'  => [
    'Chico'   => 'Chico',
    'Mediano' => 'Mediano',
    'Grande'  => 'Grande',
  ],
/* ===================== ALMACÉN [ PRODUCTOS ] ===================== */
  'select_producto_index'  => [
    ''              => 'Buscar por. . .',
    'categ'         => 'Categoría',
    'cod_barras'    => 'Código de barras',
    'etiq'          => 'Etiqueta',
    'id'            => 'ID',
    'prec_clien'    => 'Precio cliente',
    'produc'        => 'Producto',
    'prove'         => 'Proveedor',
    'sku'           => 'SKU',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_producto_de_catalogo' => [
    'Producto de catálogo'  => 'Producto de catálogo',
    'Producto externo'      => 'Producto externo',
  ],
  'select_utilidad' => [
    '.1'           => '10%',
    '.2'           => '20%',
    '.3'           => '30%',
    '.4'           => '40%',
    '.5'           => '50%',
    '.6'           => '60%',
    '.7'           => '70%',
    '.8'           => '80%',
    '.9'           => '90%',
  ],
  'select_utilidad_sin_seleccione' => [
    '.01'          => '1%',
    '.02'          => '2%',
    '.03'          => '3%',
    '.04'          => '4%',
    '.05'          => '5%',
    '.06'          => '6%',
    '.07'          => '7%',
    '.08'          => '8%',
    '.09'          => '9%',
    '.1'           => '10%',
    '.11'          => '11%',
    '.12'          => '12%',
    '.13'          => '13%',
    '.14'          => '14%',
    '.15'          => '15%',
    '.16'          => '16%',
    '.17'          => '17%',
    '.18'          => '18%',
    '.19'          => '19%',
    '.2'           => '20%',
    '.21'          => '21%',
    '.22'          => '22%',
    '.23'          => '23%',
    '.24'          => '24%',
    '.25'          => '25%',
    '.26'          => '26%',
    '.27'          => '27%',
    '.28'          => '28%',
    '.29'          => '29%',
    '.3'           => '30%',
    '.31'          => '31%',
    '.32'          => '32%',
    '.33'          => '33%',
    '.34'          => '34%',
    '.35'          => '35%',
    '.36'          => '36%',
    '.37'          => '37%',
    '.38'          => '38%',
    '.39'          => '39%',
    '.4'           => '40%',
    '.41'          => '41%',
    '.42'          => '42%',
    '.43'          => '43%',
    '.44'          => '44%',
    '.45'          => '45%',
    '.46'          => '46%',
    '.47'          => '47%',
    '.48'          => '48%',
    '.49'          => '49%',
    '.5'           => '50%',
    '.51'          => '51%',
    '.52'          => '52%',
    '.53'          => '53%',
    '.54'          => '54%',
    '.55'          => '55%',
    '.56'          => '56%',
    '.57'          => '57%',
    '.58'          => '58%',
    '.59'          => '59%',
    '.6'           => '60%',
    '.61'          => '61%',
    '.62'          => '62%',
    '.63'          => '63%',
    '.64'          => '64%',
    '.65'          => '65%',
    '.66'          => '66%',
    '.67'          => '67%',
    '.68'          => '68%',
    '.69'          => '69%',
    '.7'           => '70%',
    '.71'          => '71%',
    '.72'          => '72%',
    '.73'          => '73%',
    '.74'          => '74%',
    '.75'          => '75%',
    '.76'          => '76%',
    '.77'          => '77%',
    '.78'          => '78%',
    '.79'          => '79%',
    '.8'           => '80%',
    '.81'          => '81%',
    '.82'          => '82%',
    '.83'          => '83%',
    '.84'          => '84%',
    '.85'          => '85%',
    '.86'          => '86%',
    '.87'          => '87%',
    '.88'          => '88%',
    '.89'          => '89%',
    '.9'           => '90%',
  ],
/* ===================== ALMACÉN [ PEDIDO ACTIVO ] ===================== */
  'select_almacen_pedido_activo_index'  => [
    ''                        => 'Buscar por. . .',
  //  'usuario.email_registro'  => 'Cliente',
    'estat_alm'               => 'Estatus almacén',
    'estat_pag'               => 'Estatus pago',
    'fech_de_entreg'          => 'Fecha de entrega (YYYY-MM-DD)',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== ALMACÉN PEDIDO ACTIVO [ ARMADOS ] ===================== */
  'select_pedido_armados_index' => [
    ''            => 'Buscar por. . .',
    'nom'         => 'Armado',
    'cant'        => 'Cantidad',
    'estat'       => 'Estatus',
    'tip'         => 'Tipo',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_estatus_armado_almacen' => [
    config('app.en_espera_de_compra')       => config('app.en_espera_de_compra'),
    config('app.en_revision_de_productos')  => config('app.en_revision_de_productos'),
    config('app.productos_completos')       => config('app.productos_completos'),
    config('app.en_almacen_de_salida')      => 'Producto de STOCK',
  ],
  'select_productos_armado_index' => [
    ''            => 'Buscar por. . .',
    'cant'        => 'Cantidad',
    'produc'      => 'Producto',
    'sku'         => 'SKU',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ COTIZACIONES ] ===================== */
  'select_cotizacion_index'  => [
    ''                        => 'Buscar por. . .',
    'serie'                   => 'Serie',
    'estat'                   => 'Estatus',
    'num_pedido_gen'          => 'Num. Pedido generado',
    'valid'                   => 'Validez',
  //  'cliente.email_registro'  => 'Correo cliente',
    'tot'                     => 'Total',
    'created_at'              => 'Fecha de creación (YYYY-MM-DD)',
    'updated_at'              => 'Fecha última modificación (YYYY-MM-DD)',
  ],
/* ===================== COTIZACIONES/ARMADO [ DIRECCIONES ] ===================== */
  'select_metodo_de_entrega'  => [
    'En bodega'                         => 'En bodega',
    'Gratis'                            => 'Gratis',
    'Paquetería'                        => 'Paquetería',
    'Transporte interno de la empresa'  => 'Transporte interno de la empresa',
    'Transportes ferro'                 => 'Transportes ferro',
    'Transportes Vianey'                => 'Transportes Vianey',
    'Viaje metropolitano'               => 'Viaje metropolitano (Uber, Didi, Beat. . .)',
  ],
  'select_tipo_de_descuento'  => [
    'Sin descuento' => 'Sin descuento',
    'Manual'        => 'Manual',
    'Porcentaje'    => 'Porcentaje',
  ],
/* ===================== VENTAS [ PEDIDO ACTIVO ] ===================== */
  'select_venta_pedidoActivo_index'  => [
    ''                        => 'Buscar por. . .',
  //  'usuario.email_registro'  => 'Cliente', // este marca error
    'estat_pag'               => 'Estatus pago',
    'estat_vent_gen'          => 'Estatus venta general',
    'estat_vent_arm'          => 'Estatus venta armado(s)',
    'estat_vent_dir'          => 'Estatus venta dirección(es)',
    'fech_de_entreg'          => 'Fecha de entrega',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_entrega_express'  => [
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'es_pedido_urgente'  => [
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_se_puede_entregar_antes'  => [
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_es_de_regalo'  => [
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_tarjeta_de_felicitacion'  => [
    'Estandar'                  => 'Estandar',
    'Entregada por el cliente'  => 'Entregada por el cliente',
    'Personalizada'             => 'Personalizada',
    'Diseñada por el cliente'   => 'Diseñada por el cliente',
    'Sin tarjeta'               => 'Sin tarjeta',
  ],
/* ===================== VENTAS [ PEDIDO TERMINADO ] ===================== */
  'select_com_o_recl'  => [
    'Comentario'    => 'Comentario',
    'Reclamación'   => 'Reclamación',
  ],
  'select_abierto_cerrado'  => [
    'Abierto'   => 'Abierto',
    'Cerrado'   => 'Cerrado',
  ],
  /* =====================  PAGOS [ INDIVIDUAL ] ===================== */
  'select_pago_index'  => [
    ''                  => 'Buscar por. . .',
    'fol'               => 'Folio',
    'cod_fact'          => 'Código de facturación',
    'estat_pag'         => 'Estatus de pago',
    'form_de_pag'       => 'Forma de pago',
    'mont_de_pag'       => 'Monto de pago',
  //  'pedido.num_pedido' => 'Número de pedido',
    'created_at'        => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_forma_de_pago'  => [
    'Transferencia Canastas y Arcones S.A de C.V' => 'Transferencia Canastas y Arcones S.A de C.V',
    'Paypal'                                      => 'Paypal',
    'Tarjeta de credito (Clip)'                   => 'Tarjeta de credito (Clip)',
    'Transferencia RUTH Yolanda'                   => 'Transferencia RUTH Yolanda',
    'Efectivo (Jonathan)'                         => 'Efectivo (Jonathan)',
    'Efectivo (Gabriel)'                          => 'Efectivo (Gabriel)',
    'Efectivo (Fernando)'                         => 'Efectivo (Fernando)',
    'Cheque'                                      => 'Cheque',
    'Tarjeta de credito (Pagina)'                 => 'Tarjeta de credito (Pagina)',
    'Tarjeta de debito'                           => 'Tarjeta de debito',
  ],
  'select_estatus_pago_individual'  => [
    config('app.pendiente')  => config('app.pendiente'),
    config('app.aprobado')  => config('app.aprobado'),
    config('app.rechazado') => config('app.rechazado'),
  ],
  /* ===================== PAGOS [ FPEDIDO ] ===================== */
  'select_pago_fpedido_index'  => [
    ''                => 'Buscar por. . .',
    'estat_pag'       => 'Estatus pago',
    'num_pedido'      => 'Número de pedido',
    'mont_tot_de_ped' => 'Monto total',
  ],
  /* =====================  RASTREAR [ RASTREAR PEDIDO ] ===================== */
  'select_rastrear_pedido_index'  => [
    ''                        => 'Buscar por. . .',
    //  'usuario.email_registro'  => 'Cliente', // este marca error
    'estat_pag'               => 'Estatus pago',
    'estat_vent_gen'          => 'Estatus venta general',
    'estat_vent_arm'          => 'Estatus venta armado(s)',
    'estat_vent_dir'          => 'Estatus venta dirección(es)',
    'fech_de_entreg'          => 'Fecha de entrega',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ], 
  /* ===================== [ COSTOS DE ENVIO ] ===================== */
  	'select_foraneo_local' => [
      'Foráneo' => 'Foráneo',
      'Local' 	=> 'Local',
    ],
    'select_foraneo_local_ambos' => [
      'Foráneo'         => 'Foráneo',
      'Local' 	        => 'Local',
      'Foráneo y Local' => 'Foráneo y Local',
    ],
    'select_tipo_de_envio'  => [
      'Normal'      => 'Normal',
      'Express'     => 'Express',
    ],
    'select_tipo_de_envio_plus'  => [
      'Consolidado' => 'Consolidado',
      'Directo'     => 'Directo',
      'Normal'      => 'Normal',
      'Express'     => 'Express',
      'Paquetería'  => 'Paquetería',
    ],
    'select_tipo_de_empaque'  => [
      'Cuenta con caja de cartón'     => 'Cuenta con caja de cartón',
      'No cuenta con caja de cartón'  => 'No cuenta con caja de cartón',
    ],
    'select_transporte'  => [
      'Tráiler' => 'Tráiler',
      'Torton'  => 'Torton',
      'C. 3.5'  => 'C. 3.5',
      'C. 1.5'  => 'C. 1.5',
      'Rabón'   => 'Rabón',
    ],
  /* ===================== [ FACTURACIÓN ] ===================== */
  'select_factura_index'  => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'est_fact'      => 'Estatus factura',
    'nom_o_raz_soc' => 'Nombre o razón social',
    'rfc'           => 'RFC',
  ],
	'select_concepto' => [
		'Arcón Navideño' 		    => 'Arcón Navideño',
		'Canastas Navideñas' 	  => 'Canastas Navideñas',
		'Despensas' 			      => 'Despensas',
		'Regalo de fin de año' 	=> 'Regalo de fin de año',
  ],
  'select_uso_de_cfdi' 												                => [
		'G01 Adquisición de mercancias'									          => 'G01 Adquisición de mercancias',
		'G02 Devoluciones descuentos o bonificaciones'					  => 'G02 Devoluciones descuentos o bonificaciones',
		'G03 Gastos en general'										            	  => 'G03 Gastos en general',
		'P01 Por definir'												                  => 'P01 Por definir',
		'I01 Construcciones'											                => 'I01 Construcciones',
		'I02 Mobiliario y equipo de oficina por inversiones'		  => 'I02 Mobiliario y equipo de oficina por inversiones',
		'I03 Equipo de transporte'										            => 'I03 Equipo de transporte',
		'I04 Equipo de computo y accesorios'							        => 'I04 Equipo de computo y accesorios',
		'I05 Dados troqueles moldes matrices y herramientas'	    => 'I05 Dados troqueles moldes matrices y herramientas',
		'I06 Comunicaciones telefonicas'								          => 'I06 Comunicaciones telefonicas',
		'I07 Comunicaciones satelitales'								          => 'I07 Comunicaciones satelitales',
		'I08 Otra maquinaria y equipo'									          => 'I08 Otra maquinaria y equipo',
		'D01 honorarios médicos dentales y gastos hospitalarios' => 'D01 honorarios médicos dentales y gastos hospitalarios',
		'D02 Gastos médicos por incapacidad o discapacidad'				=> 'D02 Gastos médicos por incapacidad o discapacidad',
		'D03 Gastos funerales'											              => 'D03 Gastos funerales',
		'D04 Donativos'													                  => 'D04 Donativos',
		'D05 Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'  => 'D05 Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)',
		'D06 Aportaciones voluntarias al SAR'							        => 'D06 Aportaciones voluntarias al SAR',
		'D07 Primas por seguros de gastos médicos'						    => 'D07 Primas por seguros de gastos médicos',
		'D08 Gastos de transportación escolar obligatoria'				=> 'D08 Gastos de transportación escolar obligatoria',
		'D09 Depósitos en cuentas para el ahorro primas que tengan como base planes de pensiones'  =>'D09 Depósitos en cuentas para el ahorro primas que tengan como base planes de pensiones',
		'D10 Pagos por servicios educativos (colegiaturas)'				=> 'D10 Pagos por servicios educativos (colegiaturas)',
  ],
  'select_metodo_de_pago' 					        => [
		'PUE Pago en una sola exhibición' 		  => 'PUE Pago en una sola exhibición', 
		'PPD Pago en parcialidades o diferido'  => 'PPD Pago en parcialidades o diferido', 
  ],
  'select_forma_de_pago_factura' 							=> [
		'01 Efectivo' 								            => '01 Efectivo', 
		'02 Cheque nominativo' 						        => '02 Cheque nominativo',
		'03 Transferencia electrónica de fondos'	=> '03 Transferencia electrónica de fondos',
		'04 Tarjeta de crédito' 					        => '04 Tarjeta de crédito',
		'05 Monedero electrónico' 					      => '05 Monedero electrónico',
		'06 Dinero electrónico' 					        => '06 Dinero electrónico',
		'08 Vales de despensa' 						        => '08 Vales de despensa',
		'12 Dación en pago' 						          => '12 Dación en pago',
		'13 Pago por subrogación' 					      => '13 Pago por subrogación',
		'14 Pago por consignación' 					      => '14 Pago por consignación',
		'15 Condonación' 							            => '15 Condonación',
		'17 Compensación' 						          	=> '17 Compensación',
		'23 Novación' 								            => '23 Novación',
		'24 Confusión' 								            => '24 Confusión',
		'25 Remisión de deuda' 						        => '25 Remisión de deuda',
		'26 Prescripción o caducidad' 				    => '26 Prescripción o caducidad',
		'27 A satisfacción del acreedor' 			    => '27 A satisfacción del acreedor',
		'28 Tarjeta de débito' 						        => '28 Tarjeta de débito',
		'29 Tarjeta de servicios' 					      => '29 Tarjeta de servicios',
		'30 Aplicación de anticipos' 				      => '30 Aplicación de anticipos',
		'99 Por definir' 							            => '99 Por definir',
  ],
/* ===================== TI [ SOPORTES ] ===================== */
  'select_soporte_index'  => [
    ''              => 'Buscar por. . .',
    'emp'           => 'Empresa',
    'sol'           => 'Solicitante',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_estatus_soporte'  => [
    'Pendiente'             => 'Pendiente',
    'En espera de compra'   => 'En espera de compra',
    'Terminado'             => 'Terminado',
  ],
  'select_costos_de_envio_index'  => [
    ''              => 'Buscar por. . .',
    'id'            => '#',
    'cost_por_env'  => 'Costo por envío',
    'est'           => 'Estado',
    'met_de_entreg' => 'Método de entrega',
    'tip_env'       => 'Tipo de envío',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== PRODUCCIÓN [ PEDIDO ACTIVO ] ===================== */
  'select_produccion_pedido_activo_index'  => [
    ''                        => 'Buscar por. . .',
  //  'usuario.email_registro'  => 'Cliente',
    'estat_pag'               => 'Estatus pago',
    'estat_produc'            => 'Estatus producción',
    'fech_de_entreg'          => 'Fecha de entrega (YYYY-MM-DD)',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_bodega_donde_se_armara'  => [
    'Temas'     => 'Temas',
    'Naucalpan' => 'Naucalpan',

  ],
/* ===================== PRODUCCIÓN PEDIDO ACTIVO [ ARMADOS ] ===================== */
  'select_produccion_pedido_armados_index' => [
    ''            => 'Buscar por. . .',
    'nom'         => 'Armado',
    'cant'        => 'Cantidad',
    'estat'       => 'Estatus',
    'tip'         => 'Tipo',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_estatus_armado_produccion' => [
    config('app.en_produccion')                 => config('app.en_produccion'),
    config('app.en_almacen_de_salida')          => config('app.en_almacen_de_salida'),
    config('app.en_revision_de_productos')      => 'Productos incompletos',
  ],
  /* ===================== LOGÍSTICA [ PEDIDO ACTIVO LOCAL ] ===================== */
  'select_logistica_pedido_activo_local_index'  => [
    ''                        => 'Buscar por. . .',
  //  'usuario.email_registro'  => 'Cliente',
    'estat_pag'               => 'Estatus pago',
    'estat_produc'            => 'Estatus producción',
    'estat_log'               => 'Estatus logística',
    'fech_de_entreg'          => 'Fecha de entrega (YYYY-MM-DD)',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== LOGISTICA [ DIRECCIONES ] ===================== */
  'select_logistica_direcciones_index' => [
    ''                      => 'Buscar por. . .',
    'cod'                   => 'Número de pedido',
    'cant'                  => 'Cantidad',
    'est'                   => 'Estado',
    'estat'                 => 'Estatus',
    'met_de_entreg'         => 'Metodo de entrega',
    'tip_env'               => 'Tipo de envío',
    'nom_ref_uno'           => 'P. Recibe',
    'created_at'            => 'Fecha de registro (YYYY-MM-DD)', 
  ],
  'select_estatus_logistica_direcciones' => [
    config('app.sin_entrega_por_falta_de_informacion')  => config('app.sin_entrega_por_falta_de_informacion'),
    config('app.intento_de_entrega_fallido')            => config('app.intento_de_entrega_fallido'),
    config('app.productos_completos')                   => 'Regresar a producción',
  ],
  /* ===================== TI [ SOPORTES ] ===================== */
  'select_soporte_index'  => [
    ''              => 'Buscar por. . .',
    'emp'           => 'Empresa',
    'sol'           => 'Solicitante',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_estatus_soporte'  => [
    'Pendiente'             => 'Pendiente',
    'En espera de compra'   => 'En espera de compra',
    'Terminado'             => 'Terminado',
  ],
  /* ====================== TI [ INVENTARIO ] ===================== */
  'select_inventario_index' => [ 
    ''               => 'Buscar por. . .',
    'emp'            => 'Empresa',
    'mar'            => 'Marca',
    'num_ser'        => 'Num. Serie',
    'resp'           => 'Responsable ',
    'id_equipo'      => 'Id Equipo',
  ],
  'select_inventario_historial' => [
    ''                  => 'Buscar por. . .',
    'grup_de_falla'     => 'Agruáción de falla',
    'area_dep'          => 'Area o Departamento',
    'tec'               => 'Técnico',
  ],
/* ====================== [ MATERIALES ] ===================== */
  'select_material_index' => [ 
    ''                => 'Buscar por. . .',
    'sku'             => 'SKU',
    'produc_lin'      => 'Product Line',
    'lin_de_prod'     => 'Línea de producto',
    'prec_list_pag'   => 'Precio Lista Pagina',
    'prec_pag_al_cli' => 'Precio a cliente',
    'created_at'      => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ====================== [ MANUALES ] ===================== */
'select_manual_index' => [ 
  ''            => 'Buscar por. . .',
  'id'          => 'Id',
  'valor'       => 'Valor',
  'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
],
  'select_usu_cli_ambos' => [ 
    'Usuario' => 'Usuario',
    'Cliente' => 'Cliente',
    'Ambos'   => 'Ambos',
  ],
);