<?php
/* =====================  [ GLOBAL ] ===================== */
return array(
  'select_estado' => [
    'Aguascalientes'        => 'Aguascalientes',
    'Baja California'       => 'Baja California',
    'Baja California Sur'   => 'Baja California Sur',
    'Campeche'              => 'Campeche',
    'Ciudad de México'      => 'Ciudad de México',
    'Chihuahua'             => 'Chihuahua',
    'Chiapas'               => 'Chiapas',
    'Coahuila de Zaragoza'  => 'Coahuila de Zaragoza',
    'Colima'                => 'Colima',
    'Durango'               => 'Durango',
    'Estado de México'      => 'Estado de México',
    'Guanajuato'            => 'Guanajuato',
    'Guerrero'              => 'Guerrero',
    'Hidalgo'               => 'Hidalgo',
    'Jalisco'               => 'Jalisco',
    'Michoacán de Ocampo'   => 'Michoacán de Ocampo',
    'Morelos'               => 'Morelos',
    'Nayarit'               => 'Nayarit',
    'Nuevo León'            => 'Nuevo León',
    'Oaxaca'                => 'Oaxaca',
    'Puebla'                => 'Puebla',
    'Querétaro'             => 'Querétaro',
    'Quintana Roo'          => 'Quintana Roo' ,
    'San Luis Potosí'       => 'San Luis Potosí',
    'Sinaloa'               => 'Sinaloa',
    'Sonora'                => 'Sonora',
    'Tabasco'               => 'Tabasco',
    'Tamaulipas'            => 'Tamaulipas',
    'Tlaxcala'              => 'Tlaxcala',
    'Veracruz'              => 'Veracruz',
    'Yucatán'               => 'Yucatán',
    'Zacatecas'             => 'Zacatecas',
  ],
  'select_si_no' => [
    ''            => 'Seleccione. . .',
    'Si'          => 'Si',
    'No'          => 'No',
  ],
/* ===================== PERFIL [ PERSONALIZAR SISTEMA ] ===================== */
  'select_idioma' => [
    ''            => 'Seleccione. . .',
    'es'          => 'Español',
    'en'          => 'Ingles',
  ],
  'select_color_barra_de_navegacion'  => [
    ''                              => 'Seleccione. . .',
    'navbar-dark navbar-primary'    => 'navbar-dark navbar-primary',
    'navbar-dark navbar-secondary'  => 'navbar-dark navbar-secondary',
    'navbar-dark navbar-info'       => 'navbar-dark navbar-info',
    'navbar-dark navbar-success'    => 'navbar-dark navbar-success',
    'navbar-dark navbar-danger'     => 'navbar-dark navbar-danger',
    'navbar-dark navbar-indigo'     => 'navbar-dark navbar-indigo',
    'navbar-dark navbar-purple'     => 'navbar-dark navbar-purple',
    'navbar-dark navbar-pink'       => 'navbar-dark navbar-pink',
    'navbar-dark navbar-teal'       => 'navbar-dark navbar-teal',
    'navbar-dark navbar-cyan'       => 'navbar-dark navbar-cyan',
    'navbar-dark'                   => 'navbar-dark',
    'navbar-dark navbar-gray-dark'  => 'navbar-dark navbar-gray-dark',
    'navbar-dark navbar-gray'       => 'navbar-dark navbar-gray',
    'navbar-light'                  => 'navbar-light',
    'navbar-light navbar-warning'   => 'navbar-light navbar-warning',
    'navbar-light navbar-white'     => 'navbar-light navbar-white',
    'navbar-light navbar-orange'    => 'navbar-light navbar-orange',
  ],
  'select_color_barra_lateral_oscura_o_clara'  => [
    ''                      => 'Seleccione. . .',
    'sidebar-dark-primary'  => 'sidebar-dark-primary',
    'sidebar-dark-warning'  => 'sidebar-dark-warning',
    'sidebar-dark-info'     => 'sidebar-dark-info',
    'sidebar-dark-danger'   => 'idebar-dark-danger',
    'sidebar-dark-success'  => 'sidebar-dark-success',
    'sidebar-dark-indigo'   => 'sidebar-dark-indigo',
    'sidebar-dark-navy'     => 'sidebar-dark-navy',
    'sidebar-dark-purple'   => 'sidebar-dark-purple',
    'sidebar-dark-fuchsia'  => 'sidebar-dark-fuchsia',
    'sidebar-dark-pink'     => 'sidebar-dark-pink',
    'sidebar-dark-maroon'   => 'sidebar-dark-maroon',
    'sidebar-dark-orange'   => 'sidebar-dark-orange',
    'sidebar-dark-lime'     => 'sidebar-dark-lime',
    'sidebar-dark-teal'     => 'sidebar-dark-teal',
    'sidebar-dark-olive'    => 'sidebar-dark-olive',
    'sidebar-light-primary' => 'sidebar-light-primary',
    'sidebar-light-warning' => 'sidebar-light-warning',
    'sidebar-light-info'    => 'sidebar-light-info',
    'sidebar-light-danger'  => 'sidebar-light-danger',
    'sidebar-light-success' => 'sidebar-light-success',
    'sidebar-light-indigo'  => 'sidebar-light-indigo',
    'sidebar-light-navy'    => 'sidebar-light-navy',
    'sidebar-light-purple'  => 'sidebar-light-purple',
    'sidebar-light-fuchsia' => 'sidebar-light-fuchsia',
    'sidebar-light-pink'    => 'sidebar-light-pink',
    'sidebar-light-maroon'  => 'sidebar-light-maroon',
    'sidebar-light-orange'  => 'sidebar-light-orange',
    'sidebar-light-lime'    => 'sidebar-light-lime',
    'sidebar-light-teal'    => 'sidebar-light-teal',
    'sidebar-light-olive'   => 'sidebar-light-olive',
  ],
  'select_color_logotipo'  => [
    ''                  => 'Seleccione. . .',
    'navbar-primary'    => 'navbar-primary',
    'navbar-secondary'  => 'navbar-secondary',
    'navbar-info'       => 'navbar-info',
    'navbar-success'    => 'navbar-success',
    'navbar-danger'     => 'navbar-danger',
    'navbar-indigo'     => 'navbar-indigo',
    'navbar-purple'     => 'navbar-purple',
    'navbar-pink'       => 'navbar-pink',
    'navbar-teal'       => 'navbar-teal',
    'navbar-cyan'       => 'avbar-cyan',
    'navbar-dark'       => 'navbar-dark',
    'navbar-gray-dark'  => 'navbar-gray-dark',
    'navbar-gray'       => 'navbar-gray',
    'navbar-light'      => 'navbar-light',
    'navbar-warning'    => 'navbar-warning',
    'navbar-white'      => 'navbar-white',
    'navbar-orange'     => 'navbar-orange',
  ],
/* ===================== PERFIL [ ACTIVIDAD ] ===================== */
  'select_perfil_actividad_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'inpu'                => 'Input',
    'ant'                 => 'Valor anterior',
    'nuev'                => 'Nuevo valor',
    'created_at'          => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== PERFIL [ NOTIFICACIONES ] ===================== */
  'select_perfil_notificacion_index'  => [
    ''                    => 'Buscar por. . .',
    'data'                => 'Asunto',
    'created_at'          => 'Fecha (YYYY-MM-DD)',
  ],
  /* ===================== PERFIL [ ARCHIVOS GENERADOS ] ===================== */
  'select_perfil_archivoGenerado_index'  => [
    ''                    => 'Buscar por. . .',
    'data'                => 'Nombre',
    'created_at'          => 'Fecha (YYYY-MM-DD)',
  ],
/* ===================== SISTEMA [ PLANTILLAS ] ===================== */
  'select_plantilla_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre de la plantilla',
    'mod'                 => 'Módulo',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_modulo' => [
    ''                                          => 'Seleccione . . .',
    'Cotizaciones (Términos y condiciones)'     => 'Cotizaciones (Términos y condiciones)',
    'Clientes (Bienvenida)'                     => 'Clientes (Bienvenida)',
    'Pagos (Registrar pago)'                    => 'Pagos (Registrar pago)',
    'Pagos (Pago rechazado)'                    => 'Pagos (Pago rechazado)',
    'Perfil (Cambio de contraseña)'             => 'Perfil (Cambio de contraseña)',
    'Sistema (Restablecimiento de contraseña)'  => 'Sistema (Restablecimiento de contraseña)',
    'Usuarios (Bienvenida)'                     => 'Usuarios (Bienvenida)',
    'Ventas (Registrar pedido)'                 => 'Ventas (Registrar pedido)',
    'Ventas (Pedido cancelado)'                 => 'Ventas (Pedido cancelado)',
  ],
/* ===================== SISTEMA [ ACTIVIDAD ] ===================== */
  'select_sistema_actividad_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'inpu'                => 'Input',
    'usu'                 => 'Usuario',
    'ant'                 => 'Valor anterior',
    'nuev'                => 'Nuevo valor',
    'created_at'          => 'Fecha de modificación (YYYY-MM-DD)',
  ],
/* ===================== SISTEMA [ CATÁLOGOS ] ===================== */
  'select_catalogo_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'input'               => 'Input',
    'vista'               => 'Vista',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_input'  => [
    'Armados (Gama)'        => 'Armados (Gama)',
    'Armados (Tipo)'        => 'Armados (Tipo)',
    'Productos (Categoría)' => 'Productos (Categoría)',
    'Productos (Etiqueta)'  => 'Productos (Etiqueta)',
  ],
/* ===================== SISTEMA [ SERIES ] ===================== */
  'select_serie_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'input'               => 'Input',
    'vista'               => 'Vista',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_input_serie'      => [
    'Cotizaciones (Serie)'  => 'Cotizaciones (Serie)',
    'Pedidos (Serie)'       => 'Pedidos (Serie)',
  ],
  /* ===================== [ QUEJAS Y SUGERENCIAS ] ===================== */
  'select_qys_index'  => [
    ''                        => 'Buscar por. . .',
    'usuario.email_registro'  => 'Correo usuario',
    'depto'                   => 'Departamento',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_departamento' => [
    ''            => 'Seleccione . . .',
    'Ventas'      => 'Ventas',
    'Producción'  => 'Producción',
    'Logística'   => 'Logística',
    'Facturación' => 'Facturación',
    'Sistema'     => 'Sistema',
    'Otro'        => 'Otro',
  ],
/* ===================== [ USUARIOS ] ===================== */
  'select_usuario_index'  => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre',
    'email_registro'      => 'Correo de registro',
    'email'               => 'Correo para acceder',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ CLIENTES ] ===================== */
  'select_cliente_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre',
    'email_registro'      => 'Correo de registro',
    'email'               => 'Correo para acceder',
    'emp'                 => 'Empresa',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
  /* ===================== CLIENTES [ COTIZACIONES ] ===================== */
  'select_cliente_cotizacion_index'  => [
    ''                        => 'Buscar por. . .',
    'serie'                   => 'Serie',
    'estat'                   => 'Estatus',
    'valid'                   => 'Validez',
    'tot'                     => 'Total',
    'created_at'              => 'Fecha de creación (YYYY-MM-DD)',
  ],
/* ===================== CLIENTES [ PEDIDOS ] ===================== */
  'select_cliente_pedido_index'  => [
    ''                        => 'Buscar por. . .',
    'estat_pag'               => 'Estatus pago',
    'estat_vent_gen'          => 'Estatus venta general',
    'estat_vent_arm'          => 'Estatus venta armado(s)',
    'estat_vent_dir'          => 'Estatus venta dirección(es)',
    'fech_de_entreg'          => 'Fecha de entrega',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',    
    'entr_xprs'               => '¿Express?',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== CLIENTES [ QUEJAS Y SUGERENCIAS ] ===================== */
  'select_cliente_qys_index'  => [
    ''                        => 'Buscar por. . .',
    'depto'                   => 'Departamento',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ ROLES ] ===================== */
  'select_rol_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre del rol',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PERMISOS ] ===================== */
  'select_rol__permiso_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'nom'                 => 'Nombre del permiso',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PAPELERA DE RECICLAJE ] ===================== */
  'select_papeleraDeReciclaje_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'mod'                 => 'Módulo',
    'reg'                 => 'Registro',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== ROL CLIENTE [ DATOS FISCALES ] ===================== */
  'select_datos_fiscales_index'      => [
    ''                    => 'Buscar por. . .',
    'id'                  => 'ID',
    'rfc'                 => 'RFC',
    'nom_o_raz_soc'       => 'Razón social',
    'created_at'          => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== ROL CLIENTE [ DIRECCIONES ] ===================== */
  'select_direcciones_index'      => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'nom_ref_uno'   => 'Nombre de referencia uno',
    'nom_ref_dos'   => 'Nombre de referencia dos',
    'pais'          => 'País',
    'ciudad'        => 'Ciudad',
    'col'           => 'Colonia',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ PROVEEDOR ] ===================== */
  'select_proveedor_index'      => [
    ''              => 'Buscar por. . .',
    'id'            => 'ID',
    'raz_soc'       => 'Razón social',
    'nom_comerc'    => 'Nombre comercial',
    'nom_rep_legal' => 'Nombre del representante legal',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_fabricante_distribuidor_index'  => [
    ''              => 'Seleccione. . .',
    'Fabricante'    => 'Fabricante',
    'Distribuidor'  => 'Distribuidor',
  ],
/* ===================== PROVEEDOR [ CONTACTO ] ===================== */
  'select_contactos_proveedor_index'  => [
    ''            => 'Buscar por. . .',
    'id'          => 'ID',
    'carg'        => 'Cargo',
    'nom'         => 'Nombre',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
/* ===================== [ ARMADOS ] ===================== */
  'select_armado_index'  => [
    ''            => 'Buscar por. . .',
    'id'          => 'ID',
    'nom'         => 'Nombre',
    'prec_redond' => 'Precio redondeado',
    'sku'         => 'SKU',
    'gama'        => 'Gama',
    'created_at'  => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_tipo'  => [
    ''            => 'Seleccione. . .',
    'Producto'    => 'Producto',
    'Canasta'     => 'Canasta',
  ],
  'select_producto_armado_index'  => [
    ''                        => 'Buscar por. . .',
    'productos.categ'         => 'Categoría',
    'productos.cod_barras'    => 'Código de barras',
    'productos.etiq'          => 'Etiqueta',
    'productos.id'            => 'ID',
    'productos.prec_clien'    => 'Precio cliente',
    'productos.produc'        => 'Producto',
    'productos.prove'         => 'Proveedor',
    'productos.sku'           => 'SKU',
  ],
  'select_cantidad_table_productos_edit'  => [
    '1' => 1,
    '2' => 2,
    '3' => 3,
    '4' => 4,
    '5' => 5,
    '6' => 6,
    '7' => 7,
    '8' => 8,
    '9' => 9,
    '10' => 10,
    '11' => 11,
    '12' => 12,
    '13' => 13,
    '14' => 14,
    '15' => 15,
    '16' => 16,
    '17' => 17,
    '18' => 18,
    '19' => 19,
    '20' => 20
  ],
  'select_destacado'  => [
    ''            => 'Seleccione. . .',
    'Si'          => 'Si',
    'No'          => 'No',
  ],
/* ===================== [ PRODUCTOS ] ===================== */
  'select_producto_index'  => [
    ''              => 'Buscar por. . .',
    'categ'         => 'Categoría',
    'cod_barras'    => 'Código de barras',
    'etiq'          => 'Etiqueta',
    'id'            => 'ID',
    'prec_clien'    => 'Precio cliente',
    'produc'        => 'Producto',
    'prove'         => 'Proveedor',
    'sku'           => 'SKU',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_utilidad' => [
    ''              => 'Seleccione. . .',
    '.1'           => '10%',
    '.2'           => '20%',
    '.3'           => '30%',
    '.4'           => '40%',
    '.5'           => '50%',
    '.6'           => '60%',
    '.7'           => '70%',
    '.8'           => '80%',
    '.9'           => '90%',
  ],
  'select_utilidad_sin_seleccione' => [
    '.01'          => '1%',
    '.02'          => '2%',
    '.03'          => '3%',
    '.04'          => '4%',
    '.05'          => '5%',
    '.06'          => '6%',
    '.07'          => '7%',
    '.08'          => '8%',
    '.09'          => '9%',
    '.1'           => '10%',
    '.11'          => '11%',
    '.12'          => '12%',
    '.13'          => '13%',
    '.14'          => '14%',
    '.15'          => '15%',
    '.16'          => '16%',
    '.17'          => '17%',
    '.18'          => '18%',
    '.19'          => '19%',
    '.2'           => '20%',
    '.21'          => '21%',
    '.22'          => '22%',
    '.23'          => '23%',
    '.24'          => '24%',
    '.25'          => '25%',
    '.26'          => '26%',
    '.27'          => '27%',
    '.28'          => '28%',
    '.29'          => '29%',
    '.3'           => '30%',
    '.31'          => '31%',
    '.32'          => '32%',
    '.33'          => '33%',
    '.34'          => '34%',
    '.35'          => '35%',
    '.36'          => '36%',
    '.37'          => '37%',
    '.38'          => '38%',
    '.39'          => '39%',
    '.4'           => '40%',
    '.41'          => '41%',
    '.42'          => '42%',
    '.43'          => '43%',
    '.44'          => '44%',
    '.45'          => '45%',
    '.46'          => '46%',
    '.47'          => '47%',
    '.48'          => '48%',
    '.49'          => '49%',
    '.5'           => '50%',
    '.51'          => '51%',
    '.52'          => '52%',
    '.53'          => '53%',
    '.54'          => '54%',
    '.55'          => '55%',
    '.56'          => '56%',
    '.57'          => '57%',
    '.58'          => '58%',
    '.59'          => '59%',
    '.6'           => '60%',
    '.61'          => '61%',
    '.62'          => '62%',
    '.63'          => '63%',
    '.64'          => '64%',
    '.65'          => '65%',
    '.66'          => '66%',
    '.67'          => '67%',
    '.68'          => '68%',
    '.69'          => '69%',
    '.7'           => '70%',
    '.71'          => '71%',
    '.72'          => '72%',
    '.73'          => '73%',
    '.74'          => '74%',
    '.75'          => '75%',
    '.76'          => '76%',
    '.77'          => '77%',
    '.78'          => '78%',
    '.79'          => '79%',
    '.8'           => '80%',
    '.81'          => '81%',
    '.82'          => '82%',
    '.83'          => '83%',
    '.84'          => '84%',
    '.85'          => '85%',
    '.86'          => '86%',
    '.87'          => '87%',
    '.88'          => '88%',
    '.89'          => '89%',
    '.9'           => '90%',
  ],
/* ===================== [ COTIZACIONES ] ===================== */
  'select_cotizacion_index'  => [
    ''                        => 'Buscar por. . .',
    'serie'                   => 'Serie',
    'estat'                   => 'Estatus',
    'valid'                   => 'Validez',
    'cliente.email_registro'  => 'Correo cliente',
    'tot'                     => 'Total',
    'created_at'              => 'Fecha de creación (YYYY-MM-DD)',
  ],
/* ===================== COTIZACIONES/ARMADO [ DIRECCIONES ] ===================== */
  'select_metodo_de_entrega'  => [
    ''                                  => 'Seleccione. . .',
    'En bodega'                         => 'En bodega',
    'Gratis'                            => 'Gratis',
    'Paquetería'                        => 'Paquetería',
    'Transporte interno de la empresa'  => 'Transporte interno de la empresa',
    'Transportes ferro'                 => 'Transportes ferro',
    'Viaje metropolitano'               => 'Viaje metropolitano (Uber, Didi, Beat. . .)',
  ],
  'select_tipo_de_envio'  => [
    ''        => 'Seleccione. . .',
    'Normal'  => 'Normal',
    'Express' => 'Express',
  ],
  'select_tipo_de_descuento'  => [
    ''              => 'Seleccione. . .',
    'Sin descuento' => 'Sin descuento',
    'Manual'        => 'Manual',
    'Porcentaje'    => 'Porcentaje',
  ],
/* ===================== VENTAS [ PEDIDO ACTIVO ] ===================== */
  'select_venta_pedidoActivo_index'  => [
    ''                        => 'Buscar por. . .',
    'usuario.email_registro'  => 'Cliente', // este marca error
    'estat_pag'               => 'Estatus pago',
    'estat_vent_gen'          => 'Estatus venta general',
    'estat_vent_arm'          => 'Estatus venta armado(s)',
    'estat_vent_dir'          => 'Estatus venta dirección(es)',
    'fech_de_entreg'          => 'Fecha de entrega',
    'num_pedido'              => 'Número de pedido',
    'tot_de_arm'              => 'Total de armados',    
    'entr_xprs'               => '¿Express?',
    'created_at'              => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_entrega_express'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'es_pedido_urgente'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_se_puede_entregar_antes'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  'select_es_de_regalo'  => [
    ''    => 'Seleccione. . .',
    'Si'  => 'Si',
    'No'  => 'No',
  ],
  /* =====================  [ PAGOS ] ===================== */
  'select_pago_index'  => [
    ''              => 'Buscar por. . .',
    'created_at'    => 'Fecha de registro (YYYY-MM-DD)',
  ],
  'select_forma_de_pago'  => [
    ''                            => 'Seleccione. . .',
    'Cheque'                      => 'Cheque',
    'Efectivo'                    => 'Efectivo',
    'Paypal'                      => 'Paypal',
    'Tarjeta de credito (Pagina)' => 'Tarjeta de credito (Pagina)',
    'Tarjeta de credito (Clip)'   => 'Tarjeta de credito (Clip)',
    'Transferencia'               => 'Transferencia',
    'Otro'                        => 'Otro',
  ],
/* ===================== ALMACEN [ PRODUCTOS ] ===================== */
     'select_pedido_activo_index'  => [
      ''                 => 'Buscar por. . .',
      'arc_carg'         => 'Arcones cargados',
      'user_id'          => 'Cliente',
      'entr_xprs'        => 'Entrega express',
      'estat_alm'        => 'Estatus almacen',
      'estat_pag'        => 'Estatus pago',
      'fech_de_entreg'   => 'Fecha de entrega',
      'num_ped_unif'     => 'Número pedido unificado',
      'tot_de_arc'       => 'Total de Arcones',
      'created_at'       => 'Fecha de registro (YYYY-MM-DD)',
    ],
    'select_entrega_express' => [
      ''             => 'Seleccione. . .',
      'Si'           => 'Sí',
      'No'           => 'No',
    ],
    'select_se_puede_entregar_antes' => [
      ''             => 'Seleccione. . .',
      'Si'           => 'Sí',
      'No'           => 'No',
    ],
/* ===================== ALMAÉN [ ARMADOS ] ===================== */
    'select_pedido_armados_index' => [
      ''                           => 'Buscar por. . .',
      'pedido_armados.nom'         => 'Armado',
      'pedido_armados.cant'        => 'Cantidad',
      'pedido_armados.estat'       => 'Estatus',
      'pedido_armados.tip'         => 'Tipo',
      'pedido_armados.created_at'  => 'Fecha de registro (YYYY-MM-DD)',
    ],
    'select_estatus_armado' => [
      ''                           => 'Seleccione. . .',
      'En espera de compra'        => 'En espera de compra',
      'En revisión de productos'   => 'En revisión de productos',
      'Cancelado'                  => 'Cancelado',
    ],
    'select_productos_armado_index' => [
      ''                                          => 'Buscar por. . .',
      'pedido_armado_tiene_productos.cant'        => 'Cantidad',
      'pedido_armado_tiene_productos.produc'      => 'Producto',
      'pedido_armado_tiene_productos.sku'         => 'SKU',
      'pedido_armado_tiene_productos.created_at'  => 'Fecha de registro (YYYY-MM-DD)',
    ],
);